package databaseproject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static databaseproject.AddProduct.isNumeric;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Void
 */
public class AdProduct_AssignCategory extends javax.swing.JFrame {

    //Boolean isVisible = true;
    int itemId;
    Connection mycon;
    int adminId;
    JFrame f = new JFrame();

    public AdProduct_AssignCategory() {
        initComponents();
        mycon = db_connection.getConnection();
        UpdateScreen();

    }

    public AdProduct_AssignCategory(int itemId, int admin_id) {
        initComponents();
        this.itemId = itemId;
        adminId = admin_id;
        mycon = db_connection.getConnection();
        UpdateScreen();
    }

    public void UpdateScreen() {
        try {
            String Str_Query = "Select Category_Name FROM Category";
            PreparedStatement ps = mycon.prepareStatement(Str_Query);

            ResultSet resultSet = ps.executeQuery();
            int i = 0;
            while (resultSet.next()) {

                String Category_Name = resultSet.getString("Category_NAME");
                category.addItem(Category_Name);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Ad_ActiveSeller.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static boolean isNumeric(String strNum) {
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        addToCart = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        admin5 = new javax.swing.JLabel();
        admin7 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        admin8 = new javax.swing.JLabel();
        brandName = new javax.swing.JComboBox<>();
        modelName = new javax.swing.JComboBox<>();
        assignCategory = new javax.swing.JButton();
        back = new javax.swing.JButton();
        showBrand = new javax.swing.JButton();
        showModel = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setActionCommand("P1\np2\np3");
        menuBar3.add(menu5);

        menu6.setActionCommand("P1\np2\np3");
        menuBar3.add(menu6);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        addToCart.setBackground(new java.awt.Color(0, 77, 64));
        addToCart.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        addToCart.setForeground(new java.awt.Color(255, 255, 255));
        addToCart.setText("Add to cart");
        addToCart.setBorder(null);
        addToCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ASSIGN CATEGORY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 60));

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        admin5.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin5.setText("SELECT MODEL NAME:");
        admin5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panel.add(admin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        admin7.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin7.setText("SELECT CATEGORY NAME:");
        admin7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panel.add(admin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        category.setBackground(Color.WHITE);
        panel.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 230, 40));

        admin8.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin8.setText("SELECT BRAND NAME:");
        admin8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panel.add(admin8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        brandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandNameActionPerformed(evt);
            }
        });
        brandName.setBackground(Color.WHITE);
        panel.add(brandName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 230, 40));

        modelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNameActionPerformed(evt);
            }
        });
        modelName.setBackground(Color.WHITE);
        panel.add(modelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 230, 40));

        assignCategory.setBackground(new java.awt.Color(0, 102, 153));
        assignCategory.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        assignCategory.setForeground(new java.awt.Color(255, 255, 255));
        assignCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/approveitems(30).png"))); // NOI18N
        assignCategory.setText("ASSIGN AND APPROVE PRODUCT");
        assignCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        assignCategory.setContentAreaFilled(false);
        assignCategory.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        assignCategory.setOpaque(true);
        assignCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignCategoryActionPerformed(evt);
            }
        });
        panel.add(assignCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 580, 60));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back(60).png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        panel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 520, 130, 90));

        showBrand.setBackground(new java.awt.Color(0, 102, 153));
        showBrand.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        showBrand.setForeground(new java.awt.Color(255, 255, 255));
        showBrand.setText("SHOW BRAND NAME");
        showBrand.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        showBrand.setContentAreaFilled(false);
        showBrand.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showBrand.setOpaque(true);
        showBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBrandActionPerformed(evt);
            }
        });
        panel.add(showBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 330, -1));

        showModel.setBackground(new java.awt.Color(0, 102, 153));
        showModel.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        showModel.setForeground(new java.awt.Color(255, 255, 255));
        showModel.setText("SHOW MODEL NAME");
        showModel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        showModel.setContentAreaFilled(false);
        showModel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showModel.setOpaque(true);
        showModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showModelActionPerformed(evt);
            }
        });
        panel.add(showModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 330, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed

    }//GEN-LAST:event_addToCartActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void brandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandNameActionPerformed

    private void modelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNameActionPerformed

    private void assignCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignCategoryActionPerformed
        // TODO add your handling code here:
        if (brandName.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(f, "Missing Value, Select Brand", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (modelName.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(f, "Missing Value, Select Model", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String model = (String) modelName.getSelectedItem();
            String subcategoryName = (String) brandName.getSelectedItem();
            String subcategoryId = "";
            String brand_Id = "";
            try {
                String Str_Query = "Select Sub_Category_Id FROM sub_Category WHERE sub_category_Name= ?";
                PreparedStatement ps = mycon.prepareStatement(Str_Query);
                ps.setString(1, subcategoryName);
                ResultSet resultSet = ps.executeQuery();
                int i = 0;
                while (resultSet.next()) {
                    subcategoryId = String.valueOf(resultSet.getInt("Sub_Category_Id"));
                    //System.out.println(subcategoryId);
                }

                Str_Query = "Select Category_Type_ID FROM Sub_Category_Type WHERE sub_category_Id=? AND Category_Type_Name=?";
                ps = mycon.prepareStatement(Str_Query);
                ps.setInt(1, Integer.valueOf(subcategoryId));
                ps.setString(2, model);
                resultSet = ps.executeQuery();
                while (resultSet.next()) {
                    brand_Id = resultSet.getString("Category_Type_ID");
                    //System.out.println(brand_Id);
                }

                Str_Query = "UPDATE ITEM_DETAIL SET CATEGORY_TYPE_ID=? , APPROVAL_STATUS=?, ADMIN_ID=?  where ITEM_ID=?";
                ps = mycon.prepareStatement(Str_Query);
                ps.setInt(1, Integer.valueOf(brand_Id));
                ps.setString(2, "APPROVED");
                ps.setInt(3, adminId);
                ps.setInt(4, Integer.valueOf(itemId));
                ps.executeUpdate();

                new Ad_UnApprovedProduct(adminId).setVisible(true);
                this.setVisible(false);

            } catch (SQLException ex) {
                Logger.getLogger(Ad_ActiveSeller.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_assignCategoryActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Ad_UnApprovedProduct(adminId).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void showBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBrandActionPerformed
        // TODO add your handling code here:
        brandName.removeAllItems();
        String categoryName = (String) category.getSelectedItem();
        String categoryId = "";
        try {
            String Str_Query = "Select Category_Id FROM Category WHERE category_Name= ?";
            PreparedStatement ps = mycon.prepareStatement(Str_Query);
            ps.setString(1, categoryName);
            ResultSet resultSet = ps.executeQuery();
            while (resultSet.next()) {
                categoryId = String.valueOf(resultSet.getInt("Category_Id"));
            }

            Str_Query = "Select Sub_Category_Name FROM Sub_Category WHERE category_Id=?";
            ps = mycon.prepareStatement(Str_Query);
            ps.setInt(1, Integer.valueOf(categoryId));
            resultSet = ps.executeQuery();
            while (resultSet.next()) {
                String Sub_Category_Name = resultSet.getString("Sub_Category_Name");
                brandName.addItem(Sub_Category_Name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ad_ActiveSeller.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showBrandActionPerformed

    private void showModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showModelActionPerformed
        // TODO add your handling code here:
        if (brandName.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(f, "Missing Value, Select Brand", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {

            modelName.removeAllItems();
            String subcategoryName = (String) brandName.getSelectedItem();
            String subcategoryId = "";
            try {
                String Str_Query = "Select Sub_Category_Id FROM sub_Category WHERE sub_category_Name= ?";
                PreparedStatement ps = mycon.prepareStatement(Str_Query);
                ps.setString(1, subcategoryName);
                ResultSet resultSet = ps.executeQuery();
                int i = 0;
                while (resultSet.next()) {
                    subcategoryId = String.valueOf(resultSet.getInt("Sub_Category_Id"));
                    //System.out.println(subcategoryId);
                }

                Str_Query = "Select Category_Type_Name FROM Sub_Category_Type WHERE sub_category_Id=?";
                ps = mycon.prepareStatement(Str_Query);
                ps.setInt(1, Integer.valueOf(subcategoryId));
                resultSet = ps.executeQuery();
                while (resultSet.next()) {
                    String brand_Name = resultSet.getString("Category_Type_Name");
                    modelName.addItem(brand_Name);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ad_ActiveSeller.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_showModelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdProduct_AssignCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdProduct_AssignCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdProduct_AssignCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdProduct_AssignCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainPage().setVisible(true);
//            }
//        });
        JFrame newMain = new AdProduct_AssignCategory();
        newMain.setTitle("STAM Virtual Mart");
        newMain.setVisible(true);
        newMain.setResizable(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCart;
    private javax.swing.JLabel admin5;
    private javax.swing.JLabel admin7;
    private javax.swing.JLabel admin8;
    private javax.swing.JButton assignCategory;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> brandName;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private javax.swing.JComboBox<String> modelName;
    private javax.swing.JPanel panel;
    private javax.swing.JButton showBrand;
    private javax.swing.JButton showModel;
    // End of variables declaration//GEN-END:variables
}
