package databaseproject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Void
 */
public class Apply_Discount extends javax.swing.JFrame {

    //Boolean isVisible = true;
    Connection mycon;
    int AID;
    JFrame f = new JFrame();

    public Apply_Discount() {
        initComponents();
        mycon = db_connection.getConnection();
        UpdateScreen();
    }

    public Apply_Discount(int a) {
        initComponents();
        AID = a;
        mycon = db_connection.getConnection();
        UpdateScreen();
    }

    public void UpdateScreen() {
        try {
            String Str_Query = "Select Category_Name FROM Category";
            PreparedStatement ps = mycon.prepareStatement(Str_Query);
            ResultSet resultSet = ps.executeQuery();
            while (resultSet.next()) {

                String Category_Name = resultSet.getString("Category_NAME");
                category.addItem(Category_Name);
            }

            Str_Query = "Select Discount_Name FROM Discount";
            ps = mycon.prepareStatement(Str_Query);
            resultSet = ps.executeQuery();
            while (resultSet.next()) {
                String Discount_Name = resultSet.getString("Discount_NAME");
                discountName.addItem(Discount_Name);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Ad_ActiveSeller.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admin3 = new javax.swing.JLabel();
        Apply = new javax.swing.JButton();
        admin6 = new javax.swing.JLabel();
        endDate = new com.toedter.calendar.JDateChooser();
        startDate = new com.toedter.calendar.JDateChooser();
        admin8 = new javax.swing.JLabel();
        discountName = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        admin7 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        showBrand = new javax.swing.JButton();
        brandName = new javax.swing.JComboBox<>();
        showModel = new javax.swing.JButton();
        modelName = new javax.swing.JComboBox<>();
        admin5 = new javax.swing.JLabel();
        admin9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STAM VIRTUAL MART");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 13, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin(80).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        BackgroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to your most trusted online market place");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 113, -1, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delivering Low-Cost and High-Quality Goods Right at Your Doorstep");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        admin2.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin2.setText("ADMIN");
        admin2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(admin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, -1, -1));

        BackgroundPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 50));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Apply_Discount(70).png"))); // NOI18N
        jLabel2.setText("APPLY DISCOUNT");
        BackgroundPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        admin3.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin3.setText("VALID TILL:");
        admin3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BackgroundPanel.add(admin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, -1, -1));

        Apply.setBackground(new java.awt.Color(0, 102, 153));
        Apply.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        Apply.setForeground(new java.awt.Color(255, 255, 255));
        Apply.setText("APPLY");
        Apply.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Apply.setContentAreaFilled(false);
        Apply.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Apply.setOpaque(true);
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });
        BackgroundPanel.add(Apply, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, 190, 60));

        admin6.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin6.setText("VALID FROM:");
        admin6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BackgroundPanel.add(admin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, -1, -1));
        BackgroundPanel.add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 200, 40));
        BackgroundPanel.add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 200, 40));

        admin8.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin8.setText("SELECT DISCOUNT NAME:");
        admin8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BackgroundPanel.add(admin8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, -1, -1));

        discountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountNameActionPerformed(evt);
            }
        });
        discountName.setBackground(Color.WHITE);
        BackgroundPanel.add(discountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 280, 40));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back(60).png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        BackgroundPanel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 610, 130, 90));

        admin7.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin7.setText("SELECT CATEGORY NAME:");
        admin7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BackgroundPanel.add(admin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        category.setBackground(Color.WHITE);
        BackgroundPanel.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 230, 40));

        showBrand.setBackground(new java.awt.Color(0, 102, 153));
        showBrand.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        showBrand.setForeground(new java.awt.Color(255, 255, 255));
        showBrand.setText("SHOW BRAND NAME");
        showBrand.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        showBrand.setContentAreaFilled(false);
        showBrand.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showBrand.setOpaque(true);
        showBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBrandActionPerformed(evt);
            }
        });
        BackgroundPanel.add(showBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 330, -1));

        brandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandNameActionPerformed(evt);
            }
        });
        brandName.setBackground(Color.WHITE);
        BackgroundPanel.add(brandName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 230, 40));

        showModel.setBackground(new java.awt.Color(0, 102, 153));
        showModel.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        showModel.setForeground(new java.awt.Color(255, 255, 255));
        showModel.setText("SHOW MODEL NAME");
        showModel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        showModel.setContentAreaFilled(false);
        showModel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showModel.setOpaque(true);
        showModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showModelActionPerformed(evt);
            }
        });
        BackgroundPanel.add(showModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 330, -1));

        modelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNameActionPerformed(evt);
            }
        });
        modelName.setBackground(Color.WHITE);
        BackgroundPanel.add(modelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 230, 40));

        admin5.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin5.setText("SELECT MODEL NAME:");
        admin5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BackgroundPanel.add(admin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        admin9.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin9.setText("SELECT BRAND NAME:");
        admin9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BackgroundPanel.add(admin9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Ad_Discount_Interface(AID).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void discountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountNameActionPerformed

    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
        // TODO add your handling code here:
        if (brandName.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(f, "Missing Value, Select Brand Name", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (modelName.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(f, "Missing Value, Select Model Name", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (startDate.getDate() == null) {
            JOptionPane.showMessageDialog(f, "Missing Value, Select Start Date", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (endDate.getDate() == null) {
            JOptionPane.showMessageDialog(f, "Missing Value, Select End Date", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {

            String model = (String) modelName.getSelectedItem();
            String subcategoryName = (String) brandName.getSelectedItem();
            String subcategoryId = "";
            String brand_Id = "";
            try {
                String Str_Query = "Select Sub_Category_Id FROM sub_Category WHERE sub_category_Name= ?";
                PreparedStatement ps = mycon.prepareStatement(Str_Query);
                ps.setString(1, subcategoryName);
                ResultSet resultSet = ps.executeQuery();
                int i = 0;
                while (resultSet.next()) {
                    subcategoryId = String.valueOf(resultSet.getInt("Sub_Category_Id"));
                    //System.out.println(subcategoryId);
                }

                Str_Query = "Select Category_Type_ID FROM Sub_Category_Type WHERE sub_category_Id=? AND Category_Type_Name=?";
                ps = mycon.prepareStatement(Str_Query);
                ps.setInt(1, Integer.valueOf(subcategoryId));
                ps.setString(2, model);
                resultSet = ps.executeQuery();
                while (resultSet.next()) {
                    brand_Id = resultSet.getString("Category_Type_ID");
                    System.out.println(brand_Id);
                }
                //Update discount table start and end date
                String Discount_Name = (String) discountName.getSelectedItem();
                DateFormat fmt = new SimpleDateFormat("yyyy/MM/dd");
                String start = fmt.format(startDate.getDate());
                String end = fmt.format(endDate.getDate());
                Str_Query = "UPDATE DISCOUNT SET START_DATE=? , END_DATE=? where DISCOUNT_NAME=?";
                ps = mycon.prepareStatement(Str_Query);
                ps.setString(1, start);
                ps.setString(2, end);
                ps.setString(3, Discount_Name);
                ps.executeUpdate();

                //Extract discountid
                String discount_id = "";
                double discount_percent = 0;
                Str_Query = "Select DISCOUNT_ID,DISCOUNT_PERCENT FROM Discount WHERE DiSCOUNT_Name=?";
                ps = mycon.prepareStatement(Str_Query);
                ps.setString(1, Discount_Name);
                resultSet = ps.executeQuery();
                while (resultSet.next()) {
                    discount_id = resultSet.getString("DISCOUNT_ID");
                    discount_percent = resultSet.getInt("DISCOUNT_PERCENT");
                    System.out.println(discount_id);
                }

                //Update discount id in models table
                Str_Query = "UPDATE SUB_CATEGORY_TYPE SET DISCOUNT_ID=?  where CATEGORY_TYPE_ID=? AND SUB_CATEGORY_ID=?";
                ps = mycon.prepareStatement(Str_Query);
                ps.setInt(1, Integer.valueOf(discount_id));
                ps.setInt(2, Integer.valueOf(brand_Id));
                ps.setInt(3, Integer.valueOf(subcategoryId));
                ps.executeUpdate();

                //Update SP of all items
                discount_percent = 1 - (discount_percent / 100);
                System.out.println(discount_percent);
                Str_Query = "UPDATE item_detail SET SELLING_PRICE=COST_PRICE*? WHERE CATEGORY_TYPE_ID=?;";
                ps = mycon.prepareStatement(Str_Query);
                ps.setDouble(1, discount_percent);
                ps.setInt(2, Integer.valueOf(brand_Id));
                ps.executeUpdate();

                new Ad_Discount_Interface(AID).setVisible(true);
                this.setVisible(false);

            } catch (SQLException ex) {
                Logger.getLogger(Ad_ActiveSeller.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_ApplyActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void showBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBrandActionPerformed
        // TODO add your handling code here:
        brandName.removeAllItems();
        String categoryName = (String) category.getSelectedItem();
        String categoryId = "";
        try {
            String Str_Query = "Select Category_Id FROM Category WHERE category_Name= ?";
            PreparedStatement ps = mycon.prepareStatement(Str_Query);
            ps.setString(1, categoryName);
            ResultSet resultSet = ps.executeQuery();
            while (resultSet.next()) {
                categoryId = String.valueOf(resultSet.getInt("Category_Id"));
            }

            Str_Query = "Select Sub_Category_Name FROM Sub_Category WHERE category_Id=?";
            ps = mycon.prepareStatement(Str_Query);
            ps.setInt(1, Integer.valueOf(categoryId));
            resultSet = ps.executeQuery();
            while (resultSet.next()) {
                String Sub_Category_Name = resultSet.getString("Sub_Category_Name");
                brandName.addItem(Sub_Category_Name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ad_ActiveSeller.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showBrandActionPerformed

    private void brandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandNameActionPerformed

    private void showModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showModelActionPerformed
        // TODO add your handling code here:
        modelName.removeAllItems();
        String subcategoryName = (String) brandName.getSelectedItem();
        String subcategoryId = "";
        try {
            String Str_Query = "Select Sub_Category_Id FROM sub_Category WHERE sub_category_Name= ?";
            PreparedStatement ps = mycon.prepareStatement(Str_Query);
            ps.setString(1, subcategoryName);
            ResultSet resultSet = ps.executeQuery();
            int i = 0;
            while (resultSet.next()) {
                subcategoryId = String.valueOf(resultSet.getInt("Sub_Category_Id"));
                //System.out.println(subcategoryId);
            }

            Str_Query = "Select Category_Type_Name FROM Sub_Category_Type WHERE sub_category_Id=?";
            ps = mycon.prepareStatement(Str_Query);
            ps.setInt(1, Integer.valueOf(subcategoryId));
            resultSet = ps.executeQuery();
            while (resultSet.next()) {
                String brand_Name = resultSet.getString("Category_Type_Name");
                modelName.addItem(brand_Name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ad_ActiveSeller.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showModelActionPerformed

    private void modelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apply_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apply_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apply_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apply_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainPage().setVisible(true);
//            }
//        });
        JFrame newMain = new Apply_Discount();
        newMain.setVisible(true);
        newMain.setResizable(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel admin2;
    private javax.swing.JLabel admin3;
    private javax.swing.JLabel admin5;
    private javax.swing.JLabel admin6;
    private javax.swing.JLabel admin7;
    private javax.swing.JLabel admin8;
    private javax.swing.JLabel admin9;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> brandName;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JComboBox<String> discountName;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> modelName;
    private javax.swing.JButton showBrand;
    private javax.swing.JButton showModel;
    private com.toedter.calendar.JDateChooser startDate;
    // End of variables declaration//GEN-END:variables
}
