package databaseproject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author Void
 */
public class Item_Transaction extends javax.swing.JFrame {

    //Boolean isVisible = true;
    int OrderId ;
    Connection mycon;
    int AID;

    public Item_Transaction() {
        initComponents();
        mycon = db_connection.getConnection();
        UpdateTable();
    }

    public Item_Transaction(int O,int a) {
        initComponents();
        this.OrderId = O;
        AID =a;
        mycon = db_connection.getConnection();
        UpdateTable();
        jTable1.getTableHeader().setFont(new Font("Nirmula UI", Font.BOLD, 14));
        jTable1.setShowVerticalLines(true);
        jTable1.setShowHorizontalLines(true);
        orderId.setEditable(false);
        cardType.setEditable(false);
        CardExpDate.setEditable(false);
    }

    public void UpdateTable() {
          java.sql.Date sqlDate = null;
        try {
            String Str_Query = "SELECT itemt.item_id , itemd.item_name, itemt.quantity, itemt.line_total\n"
                    + "FROM item_transaction itemt JOIN item_detail itemd\n"
                    + "ON itemt.item_id = itemd.item_id\n"
                    + "WHERE itemt.order_id = ?;";
            PreparedStatement ps = mycon.prepareStatement(Str_Query);
            ps.setInt(1, Integer.valueOf(OrderId));
            ResultSet resultSet = ps.executeQuery();
            int i = 0;
          
            while (resultSet.next()) {
                String Item_Id = String.valueOf(resultSet.getInt("itemt.Item_ID"));
                String Item_Name = resultSet.getString("itemd.Item_NAME");
                String Quantity = String.valueOf(resultSet.getInt("Itemt.Quantity"));
                String LineTotal = String.valueOf(resultSet.getInt("Itemt.Line_total"));
                //String Cost = "0";
                String Cost = String.valueOf(Integer.parseInt(LineTotal)/Integer.parseInt(Quantity));
                String row[] = {Item_Id, Item_Name, Quantity, Cost, LineTotal};
                //System.out.println(row.toString());
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.insertRow(i, row);
                i++;   
            }
            orderId.setText(OrderId+"");
            Str_Query = "SELECT card.Bank_Name, cust.Customer_Name, card.Card_Type, custpay.Expiry "
                    + "FROM customer cust JOIN order_transaction ordert ON ordert.customer_id = cust.customer_id "
                    + "JOIN customer_payment custpay ON custpay.payment_id = ordert.payment_id "
                    + "JOIN card ON custpay.card_id = card.card_id WHERE ordert.order_id = ?";
            
            ps = mycon.prepareStatement(Str_Query);
            ps.setInt(1, Integer.valueOf(OrderId));
            resultSet = ps.executeQuery();
            
            while (resultSet.next()) {
                bankName.setText(resultSet.getString("card.Bank_Name"));
                bankName.setEditable(false);
                customerName.setText(resultSet.getString("cust.Customer_Name"));
                customerName.setEditable(false);
                cardType.setText(resultSet.getString("card.Card_Type"));
                cardType.setEditable(false);
                 sqlDate = resultSet.getDate("custpay.Expiry");
                 
                //String Cost = String.valueOf(Integer.parseInt(LineTotal)/Integer.parseInt(Quantity));   
            }
            CardExpDate.setText(sqlDate.toString());

        } catch (SQLException ex) {
            Logger.getLogger(Ad_ActiveSeller.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        CardExpDate = new javax.swing.JTextField();
        orderId = new javax.swing.JTextField();
        bankName = new javax.swing.JTextField();
        customerName = new javax.swing.JTextField();
        cardType = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STAM VIRTUAL MART");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 13, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin(80).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        BackgroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to your most trusted online market place");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 113, -1, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delivering Low-Cost and High-Quality Goods Right at Your Doorstep");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        admin2.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        admin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin2.setText("ADMIN");
        admin2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        admin2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(admin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, -1, -1));

        BackgroundPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 50));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel2.setText("Card Expiry Date");
        BackgroundPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Quantity", "Selling Price", "Line Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BackgroundPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 740, 410));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel8.setText("ORDER TRANSACTION DETAILS");
        BackgroundPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel9.setText("Order ID");
        BackgroundPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel10.setText("Bank Name");
        BackgroundPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel11.setText("Customer Name");
        BackgroundPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel12.setText("Card Type");
        BackgroundPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back(60).png"))); // NOI18N
        back.setBorder(null);
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        BackgroundPanel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 610, 130, 90));

        CardExpDate.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        CardExpDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CardExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardExpDateActionPerformed(evt);
            }
        });
        BackgroundPanel.add(CardExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 150, 30));

        orderId.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        orderId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackgroundPanel.add(orderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 210, 30));

        bankName.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        bankName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackgroundPanel.add(bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, 210, 30));

        customerName.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        customerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackgroundPanel.add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, 210, 30));

        cardType.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        cardType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTypeActionPerformed(evt);
            }
        });
        BackgroundPanel.add(cardType, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new View_Transactions(AID).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void CardExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardExpDateActionPerformed

    private void cardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainPage().setVisible(true);
//            }
//        });
        JFrame newMain = new Item_Transaction();
        newMain.setVisible(true);
        newMain.setResizable(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JTextField CardExpDate;
    private javax.swing.JLabel admin2;
    private javax.swing.JButton back;
    private javax.swing.JTextField bankName;
    private javax.swing.JTextField cardType;
    private javax.swing.JTextField customerName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField orderId;
    // End of variables declaration//GEN-END:variables
    /*static public class HeaderColor extends DefaultTableCellRenderer{
        public HeaderColor(){
            setOpaque(true);
        }
        

        public Component getTableCellRendererComponent(JTable jTable, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(jTable, value, selected, focused, row, column);
            setBackground(new java.awt.Color(0,153,204));
            //setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
            return this;
        }
    }*/

}
